development:
  <<: *default
  compile: true
  # Enable hot module replacement
  hmr: true
  # Inline should be set to true if using HMR
  inline: true
  # Don't reload on errors
  check_yarn_integrity: true
  # Enable live reload
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    # Enable live reload
    live_reload: true
    # Enable hot module replacement
    inline: true
    # Enable overlay for catching syntax errors
    overlay: true
    # Enable compression
    compress: true
    # Enable source maps
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**' 